INFO:root:called-params config/configs.yaml
INFO:root:loaded params...
{   'base_dir': '/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/',
    'data': {   'class_mapping': 'pretrained_models/class_mapping.txt',
                'species_mapping': 'pretrained_models/species_id_to_name.txt',
                'test_data': '/home/rtcalumby/adam/luciano/PlantCLEF2025/test_dataset/'},
    'k_means': {'K': 7806},
    'num_workers': 32,
    'patches': {'N': [16, 32, 64, 80, 128]},
    'pretrained_path': 'pretrained_models/vit_base_patch14_reg4_dinov2_lvd142m_pc24_onlyclassifier_then_all/model_best.pth.tar'}
INFO:root:Running... (rank: 0/4)
INFO:root:Initialized (rank/world-size) 0/4
INFO:timm.models._helpers:Loaded state_dict_ema from checkpoint 'pretrained_models/vit_base_patch14_reg4_dinov2_lvd142m_pc24_onlyclassifier_then_all/model_best.pth.tar'
{   'base_dir': '/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/',
    'data': {   'class_mapping': 'pretrained_models/class_mapping.txt',
                'species_mapping': 'pretrained_models/species_id_to_name.txt',
                'test_data': '/home/rtcalumby/adam/luciano/PlantCLEF2025/test_dataset/'},
    'k_means': {'K': 7806},
    'num_workers': 32,
    'patches': {'N': [16, 32, 64, 80, 128]},
    'pretrained_path': 'pretrained_models/vit_base_patch14_reg4_dinov2_lvd142m_pc24_onlyclassifier_then_all/model_best.pth.tar'}
Test dataset created
Test dataset created
{   'base_dir': '/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/',
    'data': {   'class_mapping': 'pretrained_models/class_mapping.txt',
                'species_mapping': 'pretrained_models/species_id_to_name.txt',
                'test_data': '/home/rtcalumby/adam/luciano/PlantCLEF2025/test_dataset/'},
    'k_means': {'K': 7806},
    'num_workers': 32,
    'patches': {'N': [16, 32, 64, 80, 128]},
    'pretrained_path': 'pretrained_models/vit_base_patch14_reg4_dinov2_lvd142m_pc24_onlyclassifier_then_all/model_best.pth.tar'}
Test dataset created
{   'base_dir': '/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/',
    'data': {   'class_mapping': 'pretrained_models/class_mapping.txt',
                'species_mapping': 'pretrained_models/species_id_to_name.txt',
                'test_data': '/home/rtcalumby/adam/luciano/PlantCLEF2025/test_dataset/'},
    'k_means': {'K': 7806},
    'num_workers': 32,
    'patches': {'N': [16, 32, 64, 80, 128]},
    'pretrained_path': 'pretrained_models/vit_base_patch14_reg4_dinov2_lvd142m_pc24_onlyclassifier_then_all/model_best.pth.tar'}
Test dataset created
INFO:root:Image [1/2105]
Process Process-1:
Traceback (most recent call last):
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/main.py", line 44, in process_main
    app_main(args=params)
  File "/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/engine_baseline.py", line 116, in main
    x = batch.to(device, non_blocking=True)
AttributeError: 'list' object has no attribute 'to'
Process Process-2:
Traceback (most recent call last):
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/main.py", line 44, in process_main
    app_main(args=params)
  File "/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/engine_baseline.py", line 116, in main
    x = batch.to(device, non_blocking=True)
AttributeError: 'list' object has no attribute 'to'
Process Process-4:
Traceback (most recent call last):
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/main.py", line 44, in process_main
    app_main(args=params)
  File "/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/engine_baseline.py", line 116, in main
    x = batch.to(device, non_blocking=True)
AttributeError: 'list' object has no attribute 'to'
terminate called after throwing an instance of 'c10::DistNetworkError'
  what():  Connection reset by peer
Exception raised from recvBytes at /opt/conda/conda-bld/pytorch_1712608885084/work/torch/csrc/distributed/c10d/Utils.hpp:672 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f4937b4d897 in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x57c69fe (0x7f4990ebe9fe in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #2: c10d::TCPStore::check(std::vector<std::string, std::allocator<std::string> > const&) + 0x2d8 (0x7f4990eba538 in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #3: c10d::ProcessGroupNCCL::heartbeatMonitor() + 0x34d (0x7f4938e1b6fd in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xd3b65 (0x7f49993b8b65 in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/../../../.././libstdc++.so.6)
frame #5: <unknown function> + 0x8609 (0x7f49a2269609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #6: clone + 0x43 (0x7f49a2034353 in /lib/x86_64-linux-gnu/libc.so.6)

terminate called after throwing an instance of 'terminate called after throwing an instance of 'c10::DistNetworkErrorc10::DistNetworkError'
'
  what():    what():  Connection reset by peer
Exception raised from recvBytes at /opt/conda/conda-bld/pytorch_1712608885084/work/torch/csrc/distributed/c10d/Utils.hpp:672 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f86ef64a897 in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x57c69fe (0x7f87489bb9fe in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #2: c10d::TCPStore::check(std::vector<std::string, std::allocator<std::string> > const&) + 0x2d8 (0x7f87489b7538 in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #3: c10d::ProcessGroupNCCL::heartbeatMonitor() + 0x34d (0x7f86f09186fd in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xd3b65 (0x7f8750eb5b65 in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/../../../.././libstdc++.so.6)
frame #5: <unknown function> + 0x8609 (0x7f8759d66609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #6: clone + 0x43 (0x7f8759b31353 in /lib/x86_64-linux-gnu/libc.so.6)
Connection reset by peer
Exception raised from recvBytes at /opt/conda/conda-bld/pytorch_1712608885084/work/torch/csrc/distributed/c10d/Utils.hpp:672 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f315f1aa897 in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x57c69fe (0x7f31b851b9fe in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #2: c10d::TCPStore::check(std::vector<std::string, std::allocator<std::string> > const&) + 0x2d8 (0x7f31b8517538 in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #3: c10d::ProcessGroupNCCL::heartbeatMonitor() + 0x34d (0x7f31604786fd in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xd3b65 (0x7f31c0a15b65 in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/../../../.././libstdc++.so.6)
frame #5: <unknown function> + 0x8609 (0x7f31c98c6609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #6: clone + 0x43 (0x7f31c9691353 in /lib/x86_64-linux-gnu/libc.so.6)


