loaded params...
{   'base_dir': '/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/',
    'data': {   'class_mapping': 'pretrained_models/class_mapping.txt',
                'species_mapping': 'pretrained_models/species_id_to_name.txt',
                'test_data': '/home/rtcalumby/adam/luciano/PlantCLEF2025/'},
    'k_means': {'K': 7806},
    'patches': {'N': [16, 32, 64, 80, 128]},
    'pretrained_path': 'pretrained_models/vit_base_patch14_reg4_dinov2_lvd142m_pc24_onlyclassifier_then_all/model_best.pth.tar'}
Traceback (most recent call last):
  File "/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/main.py", line 29, in <module>
    app_main(args=params)
  File "/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/engine_baseline.py", line 56, in main
    test_dataset, test_dataloader = build_test_dataset(image_folder=test_dir,
  File "/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/datasets/pc2025.py", line 44, in build_test_dataset
    dataset = CustomImageFolder(image_folder, transform=transform)
  File "/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/datasets/pc2025.py", line 13, in __init__
    super(CustomImageFolder, self).__init__(root, transform)
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 328, in __init__
    super().__init__(
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 150, in __init__
    samples = self.make_dataset(
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 203, in make_dataset
    return make_dataset(
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 104, in make_dataset
    raise FileNotFoundError(msg)
FileNotFoundError: Found no valid file for the classes data. Supported extensions are: .jpg, .jpeg, .png, .ppm, .bmp, .pgm, .tif, .tiff, .webp
