INFO:root:called-params config/feature_extraction.yaml
INFO:root:loaded params...
INFO:root:{'num_workers': 64, 'base_dir': '/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/', 'pretrained_path': 'pretrained_models/vit_base_patch14_reg4_dinov2_lvd142m_pc24_onlyclassifier_then_all/model_best.pth.tar', 'data': {'class_mapping': 'pretrained_models/class_mapping.txt', 'species_mapping': 'pretrained_models/species_id_to_name.txt', 'train_data': '/home/rtcalumby/adam/luciano/PlantCLEF2025/images_max_side_800/', 'output_dir': '/home/rtcalumby/adam/luciano/PlantCLEF2025/cached_features/'}}
INFO:root:Running... (rank: 0/8)
INFO:root:Initialized (rank/world-size) 0/8
INFO:timm.models._helpers:Loaded state_dict_ema from checkpoint 'pretrained_models/vit_base_patch14_reg4_dinov2_lvd142m_pc24_onlyclassifier_then_all/model_best.pth.tar'
Train dataset created
Train dataset created
Train dataset created
Train dataset created
Train dataset created
Train dataset created
Train dataset created
Train dataset created
INFO:root:Iteration [1/85]
INFO:root:Iteration [2/85]
INFO:root:Iteration [3/85]
INFO:root:Iteration [4/85]
INFO:root:Iteration [5/85]
INFO:root:Iteration [6/85]
INFO:root:Iteration [7/85]
INFO:root:Iteration [8/85]
INFO:root:Iteration [9/85]
INFO:root:Iteration [10/85]
INFO:root:Iteration [11/85]
INFO:root:Iteration [12/85]
INFO:root:Iteration [13/85]
INFO:root:Iteration [14/85]
terminate called after throwing an instance of 'c10::DistNetworkError'
terminate called after throwing an instance of 'c10::DistNetworkError'
terminate called after throwing an instance of 'c10::DistNetworkErrorterminate called after throwing an instance of ''
c10::DistNetworkError'
terminate called after throwing an instance of 'c10::DistNetworkError'
  what():  Connection reset by peer
Exception raised from recvBytes at /opt/conda/conda-bld/pytorch_1712608885084/work/torch/csrc/distributed/c10d/Utils.hpp:669 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f630458c897 in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x57c6acc (0x7f635d8fdacc in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #2: c10d::TCPStore::check(std::vector<std::string, std::allocator<std::string> > const&) + 0x2d8 (0x7f635d8f9538 in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #3: c10d::ProcessGroupNCCL::heartbeatMonitor() + 0x34d (0x7f630585a6fd in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xd3b65 (0x7f6365df7b65 in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/../../../.././libstdc++.so.6)
frame #5: <unknown function> + 0x8609 (0x7f636eca8609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #6: clone + 0x43 (0x7f636ea73353 in /lib/x86_64-linux-gnu/libc.so.6)

  what():  Connection reset by peer
Exception raised from recvBytes at /opt/conda/conda-bld/pytorch_1712608885084/work/torch/csrc/distributed/c10d/Utils.hpp:669 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f5b23ee5897 in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x57c6acc (0x7f5b7d256acc in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #2: c10d::TCPStore::check(std::vector<std::string, std::allocator<std::string> > const&) + 0x2d8 (0x7f5b7d252538 in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #3: c10d::ProcessGroupNCCL::heartbeatMonitor() + 0x34d (0x7f5b251b36fd in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xd3b65 (0x7f5b85750b65 in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/../../../.././libstdc++.so.6)
frame #5: <unknown function> + 0x8609 (0x7f5b8e601609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #6: clone + 0x43 (0x7f5b8e3cc353 in /lib/x86_64-linux-gnu/libc.so.6)
  what():  
  what():    what():  Connection reset by peer
Exception raised from recvBytes at /opt/conda/conda-bld/pytorch_1712608885084/work/torch/csrc/distributed/c10d/Utils.hpp:669 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f1730e6d897 in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x57c6acc (0x7f178a1deacc in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #2: c10d::TCPStore::check(std::vector<std::string, std::allocator<std::string> > const&) + 0x2d8 (0x7f178a1da538 in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #3: c10d::ProcessGroupNCCL::heartbeatMonitor() + 0x34d (0x7f173213b6fd in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xd3b65 (0x7f17926d8b65 in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/../../../.././libstdc++.so.6)
frame #5: <unknown function> + 0x8609 (0x7f179b589609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #6: clone + 0x43 (0x7f179b354353 in /lib/x86_64-linux-gnu/libc.so.6)
Connection reset by peer
Exception raised from recvBytes at /opt/conda/conda-bld/pytorch_1712608885084/work/torch/csrc/distributed/c10d/Utils.hpp:669 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7fac193ca897 in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x57c6acc (0x7fac7273bacc in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #2: c10d::TCPStore::check(std::vector<std::string, std::allocator<std::string> > const&) + 0x2d8 (0x7fac72737538 in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #3: c10d::ProcessGroupNCCL::heartbeatMonitor() + 0x34d (0x7fac1a6986fd in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xd3b65 (0x7fac7ac35b65 in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/../../../.././libstdc++.so.6)
frame #5: <unknown function> + 0x8609 (0x7fac83ae6609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #6: clone + 0x43 (0x7fac838b1353 in /lib/x86_64-linux-gnu/libc.so.6)


Connection reset by peer
Exception raised from recvBytes at /opt/conda/conda-bld/pytorch_1712608885084/work/torch/csrc/distributed/c10d/Utils.hpp:669 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f10f1cdd897 in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x57c6acc (0x7f114b04eacc in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #2: c10d::TCPStore::check(std::vector<std::string, std::allocator<std::string> > const&) + 0x2d8 (0x7f114b04a538 in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #3: c10d::ProcessGroupNCCL::heartbeatMonitor() + 0x34d (0x7f10f2fab6fd in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xd3b65 (0x7f1153548b65 in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/../../../.././libstdc++.so.6)
frame #5: <unknown function> + 0x8609 (0x7f115c3f9609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #6: clone + 0x43 (0x7f115c1c4353 in /lib/x86_64-linux-gnu/libc.so.6)

terminate called after throwing an instance of 'c10::DistNetworkError'
  what():  Connection reset by peer
Exception raised from recvBytes at /opt/conda/conda-bld/pytorch_1712608885084/work/torch/csrc/distributed/c10d/Utils.hpp:672 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f5c97929897 in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x57c69fe (0x7f5cf0c9a9fe in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #2: c10d::TCPStore::check(std::vector<std::string, std::allocator<std::string> > const&) + 0x2d8 (0x7f5cf0c96538 in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #3: c10d::ProcessGroupNCCL::heartbeatMonitor() + 0x34d (0x7f5c98bf76fd in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xd3b65 (0x7f5cf9194b65 in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/../../../.././libstdc++.so.6)
frame #5: <unknown function> + 0x8609 (0x7f5d02045609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #6: clone + 0x43 (0x7f5d01e10353 in /lib/x86_64-linux-gnu/libc.so.6)

terminate called after throwing an instance of 'c10::DistNetworkError'
  what():  Connection reset by peer
Exception raised from recvBytes at /opt/conda/conda-bld/pytorch_1712608885084/work/torch/csrc/distributed/c10d/Utils.hpp:669 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f2d25280897 in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x57c6acc (0x7f2d7e5f1acc in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #2: c10d::TCPStore::check(std::vector<std::string, std::allocator<std::string> > const&) + 0x2d8 (0x7f2d7e5ed538 in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so)
frame #3: c10d::ProcessGroupNCCL::heartbeatMonitor() + 0x34d (0x7f2d2654e6fd in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0xd3b65 (0x7f2d86aebb65 in /home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/site-packages/torch/lib/../../../.././libstdc++.so.6)
frame #5: <unknown function> + 0x8609 (0x7f2d8f99c609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #6: clone + 0x43 (0x7f2d8f767353 in /lib/x86_64-linux-gnu/libc.so.6)

