INFO:root:called-params config/configs.yaml
INFO:root:loaded params...
INFO:root:{'k_means': {'K': 7806}, 'patches': {'N': [16, 32, 64, 80, 128]}, 'num_workers': 32, 'base_dir': '/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/', 'pretrained_path': 'pretrained_models/vit_base_patch14_reg4_dinov2_lvd142m_pc24_onlyclassifier_then_all/model_best.pth.tar', 'data': {'class_mapping': 'pretrained_models/class_mapping.txt', 'species_mapping': 'pretrained_models/species_id_to_name.txt', 'test_data': '/home/rtcalumby/adam/luciano/PlantCLEF2025/test_dataset/'}}
INFO:root:Running... (rank: 0/4)
INFO:root:Initialized (rank/world-size) 0/4
INFO:timm.models._helpers:Loaded state_dict_ema from checkpoint 'pretrained_models/vit_base_patch14_reg4_dinov2_lvd142m_pc24_onlyclassifier_then_all/model_best.pth.tar'
Test dataset created
Test dataset created
Test dataset created
Test dataset created
INFO:root:Image [1/2105]
--- Logging error ---
Traceback (most recent call last):
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "<string>", line 1, in <module>
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/main.py", line 44, in process_main
    app_main(args=params)
  File "/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/engine_baseline.py", line 96, in main
    logger.info('Preprocessed resized patches:', patches.size())
Message: 'Preprocessed resized patches:'
Arguments: (torch.Size([8192, 3, 518, 518]),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "<string>", line 1, in <module>
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/main.py", line 44, in process_main
    app_main(args=params)
  File "/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/engine_baseline.py", line 114, in main
    logger.info('Preprocessed batch no.', i+1)
Message: 'Preprocessed batch no.'
Arguments: (1,)
--- Logging error ---
Traceback (most recent call last):
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "<string>", line 1, in <module>
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/main.py", line 44, in process_main
    app_main(args=params)
  File "/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/engine_baseline.py", line 114, in main
    logger.info('Preprocessed batch no.', i+1)
Message: 'Preprocessed batch no.'
Arguments: (2,)
INFO:root:Image [2/2105]
--- Logging error ---
Traceback (most recent call last):
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "<string>", line 1, in <module>
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/main.py", line 44, in process_main
    app_main(args=params)
  File "/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/engine_baseline.py", line 96, in main
    logger.info('Preprocessed resized patches:', patches.size())
Message: 'Preprocessed resized patches:'
Arguments: (torch.Size([8192, 3, 518, 518]),)
--- Logging error ---
Traceback (most recent call last):
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "<string>", line 1, in <module>
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/main.py", line 44, in process_main
    app_main(args=params)
  File "/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/engine_baseline.py", line 114, in main
    logger.info('Preprocessed batch no.', i+1)
Message: 'Preprocessed batch no.'
Arguments: (1,)
--- Logging error ---
Traceback (most recent call last):
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "<string>", line 1, in <module>
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/main.py", line 44, in process_main
    app_main(args=params)
  File "/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/engine_baseline.py", line 114, in main
    logger.info('Preprocessed batch no.', i+1)
Message: 'Preprocessed batch no.'
Arguments: (2,)
INFO:root:Image [3/2105]
--- Logging error ---
Traceback (most recent call last):
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "<string>", line 1, in <module>
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/rtcalumby/miniconda3/envs/fgdcc/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/main.py", line 44, in process_main
    app_main(args=params)
  File "/home/rtcalumby/adam/luciano/PlantCLEF2025/PlantCLEF2025/engine_baseline.py", line 96, in main
    logger.info('Preprocessed resized patches:', patches.size())
Message: 'Preprocessed resized patches:'
Arguments: (torch.Size([8192, 3, 518, 518]),)
slurmstepd: error: *** JOB 5458 ON hgx CANCELLED AT 2025-04-16T09:24:21 ***
